version: "3.9"
services:
  web:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json