name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.AZURE_VM_SSH_KEY }}

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          cd ${{ secrets.PROJECT_PATH }} &&
          cd mclips-client &&
          git reset --hard &&
          git clean -fd &&
          git pull origin main &&
          cd ../mclips-server &&
          git reset --hard &&
          git clean -fd &&
          git pull origin main &&
          cd .. &&
          docker-compose down &&
          docker-compose up --build -d
        EOF